import { mkdirSync, mkdtempSync, rmSync, statSync, unlinkSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type Indexer, openIndex, type Store } from "../src/engine/index.ts";

let store: Store;
let indexer: Indexer;
let dir: string;
const has = (name: string) => store.definitions(name, 5).length > 0;
const write = (rel: string, body: string) => writeFileSync(join(dir, rel), body);

beforeAll(async () => {
	dir = mkdtempSync(join(tmpdir(), "codeindex-inc-"));
	write("a.ts", "export function aa() {}\n");
	write("b.ts", "export function bb() {}\n");
	const opened = openIndex({ root: dir, dbPath: join(dir, ".idx.db") });
	store = opened.store;
	indexer = opened.indexer;
	await indexer.sync();
});
afterAll(() => {
	store.close();
	rmSync(dir, { recursive: true, force: true });
});

describe("incremental sync (R6)", () => {
	it("starts from a correct full index", () => {
		expect(has("aa")).toBe(true);
		expect(has("bb")).toBe(true);
		expect(has("cc")).toBe(false);
	});

	it("re-indexes a modified file named in `only`", async () => {
		write("a.ts", "export function aa() {}\nexport function cc() {}\n");
		await indexer.sync({ only: ["a.ts"] });
		expect(has("cc")).toBe(true);
	});

	it("content-checks a watcher path even when mtime and size are unchanged", async () => {
		const path = join(dir, "same-meta.ts");
		writeFileSync(path, "export function oldName() {}\n");
		await indexer.sync({ only: ["same-meta.ts"] });
		const before = statSync(path);
		writeFileSync(path, "export function newName() {}\n");
		utimesSync(path, before.atime, before.mtime);

		await indexer.sync({ only: ["same-meta.ts"] });
		expect(has("oldName")).toBe(false);
		expect(has("newName")).toBe(true);
	});

	it("keeps watcher paths under hidden and virtual-environment directories excluded", async () => {
		mkdirSync(join(dir, ".hidden"));
		mkdirSync(join(dir, ".venv"));
		writeFileSync(join(dir, ".hidden/hidden.ts"), "export function hiddenByWatcher() {}\n");
		writeFileSync(join(dir, ".venv/hidden.py"), "def virtualenv_symbol():\n    pass\n");

		await indexer.sync({ only: [".hidden/hidden.ts", ".venv/hidden.py"] });
		expect(has("hiddenByWatcher")).toBe(false);
		expect(has("virtualenv_symbol")).toBe(false);
	});

	it("indexes a newly-added file named in `only`", async () => {
		write("c.ts", "export function ee() {}\n");
		await indexer.sync({ only: ["c.ts"] });
		expect(has("ee")).toBe(true);
	});

	it("is truly incremental: a change to a file NOT in `only` is ignored, then caught by a full sync", async () => {
		write("b.ts", "export function bb() {}\nexport function dd() {}\n");
		await indexer.sync({ only: ["a.ts"] });
		expect(has("dd")).toBe(false);
		await indexer.sync();
		expect(has("dd")).toBe(true);
	});

	it("rebuilds cross-file occurrences after an `only` change", async () => {
		write("callee.ts", "export function target() {}\n");
		write("caller.ts", 'import { target } from "./callee";\nexport function run() {}\n');
		await indexer.sync(); // full: run does not call target yet
		expect(store.callers("target", 5)).toHaveLength(0);
		write("caller.ts", 'import { target } from "./callee";\nexport function run() { target(); }\n');
		await indexer.sync({ only: ["caller.ts"] });
		expect(store.callers("target", 5).some((h) => h.enclosing === "run")).toBe(true);
	});

	it("deletes an indexed file that becomes too large to index", async () => {
		write("big.ts", "export function bigfn() {}\n");
		await indexer.sync({ only: ["big.ts"] });
		expect(has("bigfn")).toBe(true);
		write("big.ts", `export function bigfn() {}\n// ${"x".repeat(600_000)}\n`); // > 512 KiB cap
		await indexer.sync({ only: ["big.ts"] });
		expect(has("bigfn")).toBe(false);
	});

	it("drops a file that becomes generated (a `do not edit` banner is added)", async () => {
		write("gen.ts", "export function genfn() {}\n");
		await indexer.sync({ only: ["gen.ts"] });
		expect(has("genfn")).toBe(true);
		write("gen.ts", "// Code generated by tool. DO NOT EDIT.\nexport function genfn() {}\n");
		await indexer.sync({ only: ["gen.ts"] });
		expect(has("genfn")).toBe(false);
	});

	it("re-evaluates source-precedence siblings (.ts supersedes .js)", async () => {
		write("p.js", "export function jsfn() {}\n");
		await indexer.sync({ only: ["p.js"] });
		expect(has("jsfn")).toBe(true);
		// Adding the TS source supersedes the compiled .js — the sibling must be dropped.
		write("p.ts", "export function tsfn() {}\n");
		await indexer.sync({ only: ["p.ts"] });
		expect(has("tsfn")).toBe(true);
		expect(has("jsfn")).toBe(false);
		// Removing the source resurrects the .js sibling.
		unlinkSync(join(dir, "p.ts"));
		await indexer.sync({ only: ["p.ts"] });
		expect(has("jsfn")).toBe(true);
	});

	it("removes a deleted file named in `only` without wiping unrelated symbols", async () => {
		unlinkSync(join(dir, "a.ts"));
		const result = await indexer.sync({ only: ["a.ts"] });
		expect(result.removedFiles).toBe(1);
		expect(has("aa")).toBe(false);
		expect(has("cc")).toBe(false);
		expect(has("bb")).toBe(true);
	});
});
