import { describe, expect, it } from "vitest";
import { shouldIndexSource } from "../src/engine/indexer/source-filter.ts";
import type { FileStat, FileSystem } from "../src/engine/ports.ts";

/** Minimal FileSystem fake: no sibling files exist. */
const fs: FileSystem = {
	readFile: () => undefined,
	stat: (): FileStat | undefined => undefined,
	exists: () => false,
	walk: () => [],
};

describe("shouldIndexSource", () => {
	it("excludes generated banners (tool attribution / DO NOT EDIT)", () => {
		expect(
			shouldIndexSource(fs, "/repo", "a.ts", "// Code generated by protoc. DO NOT EDIT.\nexport const x = 1;"),
		).toBe(false);
		expect(shouldIndexSource(fs, "/repo", "b.ts", "/* @generated */\nexport const y = 2;")).toBe(false);
	});

	it("keeps files that merely discuss codegen in prose", () => {
		const source = "/**\n * Indexing generated code wastes budget.\n */\nexport function f() {}";
		expect(shouldIndexSource(fs, "/repo", "doc.ts", source)).toBe(true);
	});

	it("excludes generated directories and name patterns", () => {
		expect(shouldIndexSource(fs, "/repo", "src/__generated__/api.ts")).toBe(false);
		expect(shouldIndexSource(fs, "/repo", "src/api.pb.go")).toBe(false);
		expect(shouldIndexSource(fs, "/repo", "src/types.d.ts")).toBe(false);
	});

	it("keeps ordinary source files", () => {
		expect(shouldIndexSource(fs, "/repo", "src/app.ts", "export const z = 3;")).toBe(true);
	});
});
