/**
 * Generated-artifact and source-precedence filters.
 *
 * Indexing generated code (protobufs, codegen, minified bundles) wastes budget and
 * pollutes results; and when both `.ts` and a compiled `.js` exist, only the source
 * should be indexed.
 */

import { extname, join } from "node:path";
import type { FileSystem } from "../ports.ts";

const PRUNED_PATH_SEGMENTS = new Set([
	".git",
	".hg",
	".svn",
	".codeindex",
	"node_modules",
	"dist",
	"build",
	"out",
	"target",
	"vendor",
	"coverage",
	"tmp",
	"venv",
	".venv",
	"__pycache__",
]);

const GENERATED_DIRS = new Set([
	"generated",
	"__generated__",
	"codegen",
	"__codegen__",
	"generated-sources",
	"generated_sources",
	"openapi-generated",
	".openapi-generator",
]);

const GENERATED_NAMES = [
	/\.generated\./i,
	/_generated\./i,
	/_gen\./i,
	/\.pb\./i,
	/_pb2\.py$/i,
	/_sqlc\.go$/i,
	/\.g\.[^.]+$/i,
	/\.min\.[^.]+$/i,
	/(?:^|[.-])(?:bundle|chunk)(?:[.-]|$)/i,
	/\.d\.(?:ts|mts|cts)$/i,
];

// Banner conventions only — tool attribution ("generated by X") or an edit warning.
// The bare phrase "generated code" is deliberately excluded: it appears in prose
// (docs/comments) and is not a reliable generated-file marker.
const GENERATED_HEADERS = [
	/@generated/i,
	/\bgenerated by\b/i,
	/\bdo not edit\b/i,
	/\bautomatically generated\b/i,
	/\bcode generated .* do not edit\b/i,
];

const SOURCE_PRECEDENCE: Record<string, string[]> = {
	".js": [".ts", ".tsx"],
	".mjs": [".mts", ".ts"],
	".cjs": [".cts", ".ts"],
	".jsx": [".tsx"],
};

export function shouldIndexSource(fs: FileSystem, repoRoot: string, relativePath: string, source?: string): boolean {
	if (isPrunedSourcePath(relativePath)) return false;
	if (fs.isIgnored?.(repoRoot, relativePath)) return false;
	const parts = relativePath.replaceAll("\\", "/").split("/");
	if (parts.some((part) => GENERATED_DIRS.has(part.toLowerCase()))) return false;
	const name = parts.at(-1) ?? relativePath;
	if (GENERATED_NAMES.some((pattern) => pattern.test(name))) return false;
	if (hasHigherPrecedenceSibling(fs, repoRoot, relativePath)) return false;
	// Generated banners always live in the top-of-file comment block; scanning raw
	// source would misfire on any file that merely discusses codegen in its body.
	if (source !== undefined && GENERATED_HEADERS.some((pattern) => pattern.test(leadingCommentBanner(source)))) {
		return false;
	}
	return true;
}

/** Whether a repo-relative path is outside the source walk's supported boundary. */
export function isPrunedSourcePath(relativePath: string): boolean {
	return relativePath
		.replaceAll("\\", "/")
		.split("/")
		.some((segment) => segment.startsWith(".") || PRUNED_PATH_SEGMENTS.has(segment));
}

/** Collect the leading comment/blank lines (the banner), stopping at the first code line. */
function leadingCommentBanner(source: string): string {
	const banner: string[] = [];
	let inBlock = false;
	for (const rawLine of source.split("\n", 40)) {
		const line = rawLine.trim();
		if (inBlock) {
			banner.push(line);
			if (line.includes("*/")) inBlock = false;
			continue;
		}
		if (line === "" || line.startsWith("#!")) continue;
		if (line.startsWith("//") || line.startsWith("#")) {
			banner.push(line);
			continue;
		}
		if (line.startsWith("/*")) {
			banner.push(line);
			if (!line.includes("*/")) inBlock = true;
			continue;
		}
		break; // first real code line ends the banner.
	}
	return banner.join("\n");
}

function hasHigherPrecedenceSibling(fs: FileSystem, repoRoot: string, relativePath: string): boolean {
	const extension = extname(relativePath).toLowerCase();
	const preferred = SOURCE_PRECEDENCE[extension];
	if (!preferred) return false;
	const stem = relativePath.slice(0, -extension.length);
	return preferred.some((candidate) => fs.exists(join(repoRoot, `${stem}${candidate}`)));
}

/**
 * Lower-precedence sibling paths that `relativePath` supersedes (e.g. `a.ts` → `a.js`).
 * An incremental sync must re-evaluate these when a higher-precedence source is added or
 * removed, since their indexability depends on whether this file exists.
 */
export function precedenceSiblings(relativePath: string): string[] {
	const extension = extname(relativePath).toLowerCase();
	if (!extension) return [];
	const stem = relativePath.slice(0, -extension.length);
	const siblings: string[] = [];
	for (const [lowerExt, preferred] of Object.entries(SOURCE_PRECEDENCE)) {
		if (preferred.includes(extension)) siblings.push(`${stem}${lowerExt}`);
	}
	return siblings;
}
